"use client";

import Image from "next/image";
import Link from "next/link";
import { motion, type Variants } from "framer-motion";
import { ArrowRight, Bot, Clock3, Landmark, Languages, Lightbulb, MapPin, ShieldCheck, Wallet } from "lucide-react";

const reveal: Variants = { hidden: { opacity: 0, y: 24 }, visible: { opacity: 1, y: 0, transition: { duration: 0.75, ease: "easeOut" } } };
const imageReveal: Variants = { hidden: { opacity: 0, y: 34, scale: 0.985 }, visible: { opacity: 1, y: 0, scale: 1, transition: { duration: 0.95, ease: "easeOut" } } };
const hotspotReveal: Variants = { hidden: { opacity: 0, scale: 0.82 }, visible: (index: number) => ({ opacity: 1, scale: 1, transition: { delay: 0.58 + index * 0.16, duration: 0.5, ease: "easeOut" } }) };

const hotspots = [
  { number: "01", title: "CULTURE", label: "Understand how people live.", detail: "Remove your shoes before entering many traditional homes and ryokan.", position: "left-[12%] top-[40%]", panelPosition: "right-7 left-auto top-16 origin-top-right", Icon: Landmark },
  { number: "02", title: "LOCAL TIPS", label: "Discover what travellers often miss.", detail: "Explore quieter lanes and neighbourhoods beyond the main temple routes.", position: "right-[10%] top-[33%]", Icon: Lightbulb },
  { number: "03", title: "DO'S & DON'TS", label: "Know what is respectful before you arrive.", detail: "Quiet voices and respectful behaviour are expected in many temples.", position: "left-[36%] top-[61%]", panelPosition: "right-7 left-auto top-16 origin-top-right", Icon: Languages },
  { number: "04", title: "SAFETY & ESSENTIALS", label: "Know what you need before you go.", detail: "Keep emergency contacts and important documents accessible.", position: "right-[12%] bottom-[10%]", panelPosition: "right-7 left-auto top-16 origin-top-right", Icon: ShieldCheck },
  { number: "05", title: "COVOYAGE AI", label: "Plan your journey. Ask your questions.", detail: "Create itineraries and ask destination-specific questions from the local vibe experience.", position: "left-[12%] top-[90%]", panelPosition: "right-7 left-auto top-16 origin-top-right", Icon: Bot },
];
const metadata = [ { label: "Language", value: "Japanese", Icon: Languages }, { label: "Currency", value: "JPY", Icon: Wallet }, { label: "Time Zone", value: "JST", Icon: Clock3 }, { label: "Safety", value: "High", Icon: ShieldCheck } ];

export function MasterLocalVibeSection() {
  return (
    <section className="relative overflow-hidden scroll-mt-28 bg-[#050505] px-8 pb-24 pt-6 text-[#f8f4ea] sm:px-12 lg:px-16 lg:pb-32" id="master-local-vibe">
      <div className="absolute inset-0"><Image alt="Atmospheric Kyoto street and temple scene" className="object-cover object-[42%_center] brightness-[1.14]" fill sizes="100vw" src="https://images.unsplash.com/photo-1493976040374-85c8e12f0c0e?auto=format&fit=crop&w=1600&q=82" /><div className="absolute inset-0 bg-[linear-gradient(90deg,rgba(5,5,5,0.5)_0%,rgba(5,5,5,0.42)_24%,rgba(5,5,5,0.3)_48%,rgba(5,5,5,0.16)_72%,rgba(5,5,5,0.06)_100%)]" /><div className="absolute inset-0 bg-[linear-gradient(180deg,#050505_0%,rgba(5,5,5,0.46)_10%,rgba(5,5,5,0.04)_34%,rgba(5,5,5,0.1)_68%,#050505_100%)]" /></div>
      <motion.div className="relative z-10 mx-auto max-w-7xl" initial="hidden" whileInView="visible" viewport={{ once: true, amount: 0.18 }}>
        <motion.div className="flex items-center gap-8" variants={reveal}><h2 className="shrink-0 text-xl font-semibold uppercase tracking-[0.18em] sm:text-3xl sm:tracking-[0.22em] lg:text-4xl">Master The Local Vibe</h2><div className="h-px flex-1 bg-white/28" /></motion.div>
        <div className="mt-10 grid gap-10 lg:grid-cols-[0.36fr_0.64fr] lg:items-end lg:gap-10"><motion.div className="max-w-lg lg:-translate-y-8" variants={reveal}><p className="font-serif text-3xl leading-tight text-white sm:text-4xl lg:text-[2.8rem]">Don&apos;t just visit a place. Understand it.</p><p className="mt-7 text-base leading-8 text-white/78">Discover the culture, customs, hidden gems, local wisdom, and practical knowledge that turn a trip into a deeper experience.</p><Link className="group mt-9 inline-flex items-center gap-5 border border-white/18 bg-white/10 px-8 py-4 text-sm font-semibold text-white backdrop-blur-2xl transition duration-300 hover:border-white/32 hover:bg-white/18" href="/explore"><span>Explore the Local Vibe</span><ArrowRight className="h-5 w-5 transition-transform duration-300 group-hover:translate-x-1" /></Link></motion.div>
          <motion.div className="relative -mx-8 min-h-[34rem] overflow-visible sm:-mx-12 sm:min-h-[40rem] lg:-mr-16 lg:ml-0 lg:min-h-[44rem]" variants={imageReveal}>
            <motion.div className="absolute left-4 top-5 border border-white/12 bg-black/42 p-4 backdrop-blur-xl sm:left-5 sm:top-8 lg:left-2" initial={{ opacity: 0, y: 16 }} transition={{ delay: 0.45, duration: 0.55, ease: "easeOut" }} viewport={{ once: true }} whileInView={{ opacity: 1, y: 0 }}><p className="flex items-center gap-2 text-xs font-semibold uppercase tracking-[0.28em] text-white/82"><MapPin className="h-4 w-4" strokeWidth={1.5} />Kyoto, Japan</p><div className="mt-4 grid grid-cols-2 gap-x-6 gap-y-3">{metadata.map(({ Icon, label, value }) => <div key={label}><p className="flex items-center gap-1.5 text-[0.62rem] uppercase tracking-[0.22em] text-white/56"><Icon className="h-3.5 w-3.5" strokeWidth={1.5} />{label}</p><p className="mt-1 text-sm text-white/84">{value}</p></div>)}</div></motion.div>
            <motion.svg aria-hidden="true" className="absolute inset-0 z-10 hidden h-full w-full sm:block" fill="none" viewBox="0 0 100 100"><motion.path d="M12 40 C38 31 62 30 90 33 C70 46 52 54 36 61 C52 70 70 78 88 84 C66 90 38 94 16 96" initial={{ pathLength: 0, opacity: 0 }} stroke="rgba(255,255,255,0.58)" strokeDasharray="1.8 2.8" strokeLinecap="round" strokeWidth="0.42" transition={{ delay: 0.75, duration: 1, ease: "easeInOut" }} viewport={{ once: true }} whileInView={{ pathLength: 1, opacity: 1 }} /></motion.svg>
            {hotspots.map(({ Icon, detail, label, number, panelPosition = "left-7 top-16 origin-top-left", position, title }, index) => <motion.button className={`group absolute z-20 hover:z-50 focus-visible:z-50 ${position} max-w-[15rem] text-left outline-none`} custom={index} initial="hidden" key={title} type="button" variants={hotspotReveal} viewport={{ once: true, amount: 0.4 }} whileHover={{ scale: 1.035 }} whileInView="visible"><span className="flex items-center gap-3 border border-white/14 bg-black/38 px-3 py-2 text-white shadow-2xl shadow-black/25 backdrop-blur-xl transition duration-300 group-hover:border-white/32 group-hover:bg-black/58"><span className="relative flex h-5 w-5 items-center justify-center rounded-full bg-white text-black transition duration-300 group-hover:scale-125"><span className="absolute h-10 w-10 rounded-full border border-white/28 transition duration-300 group-hover:scale-110 group-hover:border-white/50" /><Icon className="h-3 w-3" strokeWidth={1.7} /></span><span><span className="block text-[0.66rem] font-semibold uppercase tracking-[0.24em] text-white">{number} {title}</span><span className="mt-1 block text-xs leading-5 text-white/74 transition duration-300 group-hover:text-white/90">{label}</span></span></span><span className={`pointer-events-none absolute z-30 block w-64 scale-95 border border-white/14 bg-black/68 p-4 text-white opacity-0 shadow-2xl shadow-black/35 backdrop-blur-xl transition duration-300 group-hover:scale-100 group-hover:opacity-100 ${panelPosition}`}><span className="flex items-center gap-2 text-[0.62rem] font-semibold uppercase tracking-[0.24em] text-white/64"><Icon className="h-4 w-4" strokeWidth={1.5} />Local intelligence</span><span className="mt-3 block text-sm leading-6 text-white/88">{detail}</span></span></motion.button>)}
          </motion.div></div>
      </motion.div>
    </section>
  );
}
